### ISSUE TITLE
Implement Pow for BigUint and BigInt

### ISSUE THREAD

**Issue by clarcharr** [rust-num/num-bigint#29]
See rust-num/num-traits#38 for details on this trait.

**Comment by vks** [comment]
Is this necessary given that it is implemented in `num-traits` now?

**Comment by cuviper** [comment]
What do you mean?  `Pow` is defined in `num-traits`, and implemented for the primitive types, but we need to implement it here for bigints.

**Comment by vks** [comment]
I thought `num-traits` provided a generic implementation, but apparently that is not the case.

**Comment by thomwiggers** [comment]
Let's see if I can do this – I need in anyhow.

**Comment by vks** [comment]
@cuviper I found it: [num_traits::pow](https://docs.rs/num-traits/0.2.5/num_traits/pow/fn.pow.html). This should work for `BigInt` as well. (Something like `powm` in [this `num-integer` PR](https://github.com/rust-num/num-integer/pull/10) would probably be more efficient though.)

**Comment by cuviper** [comment]
> I found it: num_traits::pow. This should work for BigInt as well.

Yes, but that only works by-value with a `usize` exponent.  The `Pow` trait is more flexible.

> (Something like powm in this num-integer PR would probably be more efficient though.)

Modular `pow` is a different thing though -- and FWIW we do have inherent `modpow` methods here.

**Comment by vks** [comment]
> Yes, but that only works by-value with a usize exponent. The Pow trait is more flexible.

A `u32` exponent should be enough, and by-value is more efficient.

**Comment by windelbouwman** [comment]
I'm interested in this pow function, will there be a new release of this crate at some point containing pow, or is there work left to do?

**Comment by cuviper** [comment]
Thanks for the reminder - I've published num-bigint 0.2.1.

**Comment by peterbraden** [comment]
Still not updated in num? I get:
`    Updating crates.io index
 Downloading num v0.2.0
 Downloading num-bigint v0.2.1
 Downloading num-rational v0.2.1
   Compiling num-integer v0.1.39
   Compiling num-iter v0.1.37
   Compiling num-complex v0.2.1
   Compiling num-bigint v0.2.1
   Compiling num-rational v0.2.1
   Compiling num-bigint v0.1.40
error[E0277]: the trait bound `biguint::BigUint: num_traits::Num` is not satisfied`

**Comment by cuviper** [comment]
@peterbraden Somehow you have both new and old, `Compiling num-bigint v0.2.1` and `Compiling num-bigint v0.1.40`.  Only 0.2.1 implements `Pow`.

Your output doesn't show which `num-traits` you're compiling, but your two `num-bigint`s will also require `num-traits` 0.2 and 0.1.  That would be OK for `Num` (your error message) if the latter were 0.1.43, as that just re-exports the 0.2 versions.  Alternatively, `num-bigint` 0.1.41 started using `num-traits` 0.2 as well, but it still won't have `Pow`.

**Comment by peterbraden** [comment]
I did a cargo update and all worked, not sure how I got into that state, thanks!
